src/Entity/Agence.php
<?php

namespace App\Entity;

use App\Repository\AgenceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AgenceRepository::class)
 */
class Agence
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=8)
     */
    private $tel_agence;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\OneToMany(targetEntity=Voiture::class, mappedBy="agence")
     */
    private $voitures;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="agence")
     */
    private $users;

    public function __construct()
    {
        $this->voitures = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTelAgence(): ?string
    {
        return $this->tel_agence;
    }

    public function setTelAgence(string $tel_agence): self
    {
        $this->tel_agence = $tel_agence;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * @return Collection|Voiture[]
     */
    public function getVoitures(): Collection
    {
        return $this->voitures;
    }

    public function addVoiture(Voiture $voiture): self
    {
        if (!$this->voitures->contains($voiture)) {
            $this->voitures[] = $voiture;
            $voiture->setAgence($this);
        }

        return $this;
    }

    public function removeVoiture(Voiture $voiture): self
    {
        if ($this->voitures->removeElement($voiture)) {
            // set the owning side to null (unless already changed)
            if ($voiture->getAgence() === $this) {
                $voiture->setAgence(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setAgence($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getAgence() === $this) {
                $user->setAgence(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return $this->nom;
    }
}

src/Form/AgenceType.php
<?php

namespace App\Form;

use App\Entity\Agence;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AgenceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('tel_agence')
            ->add('adresse')
            ->add('ville')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Agence::class,
        ]);
    }
}

src/Controller/AgenceController.php
<?php

namespace App\Controller;

use App\Entity\Agence;
use App\Form\AgenceType;
use App\Repository\AgenceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/agence")
 */
class AgenceController extends AbstractController
{
    /**
     * @Route("/", name="agence_index", methods={"GET"})
     */
    public function index(AgenceRepository $agenceRepository): Response
    {
        return $this->render('agence/index.html.twig', [
            'agences' => $agenceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="agence_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $agence = new Agence();
        $form = $this->createForm(AgenceType::class, $agence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($agence);
            $entityManager->flush();

            return $this->redirectToRoute('agence_index');
        }

        return $this->render('agence/new.html.twig', [
            'agence' => $agence,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="agence_show", methods={"GET"})
     */
    public function show(Agence $agence): Response
    {
        return $this->render('agence/show.html.twig', [
            'agence' => $agence,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="agence_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Agence $agence): Response
    {
        $form = $this->createForm(AgenceType::class, $agence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('agence_index');
        }

        return $this->render('agence/edit.html.twig', [
            'agence' => $agence,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="agence_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Agence $agence): Response
    {
        if ($this->isCsrfTokenValid('delete'.$agence->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($agence);
            $entityManager->flush();
        }

        return $this->redirectToRoute('agence_index');
    }
}

templates/agence/_delete_form.html.twig
<form method="post" action="{{ path('agence_delete', {'id': agence.id}) }}" onsubmit="return confirm('Etes-vous sur vous voulez supprimer cet élement ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ agence.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/agence/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Confirmer') }}</button>
{{ form_end(form) }}

templates/agence/edit.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Modifier Agence{% endblock %}

{% block main %}
    <h1>Modifier Agence</h1>

    {{ include('agence/_form.html.twig', {'button_label': 'Confirmer'}) }}

    <a href="{{ path('agence_index') }}">retour vers liste</a>

    {{ include('agence/_delete_form.html.twig') }}
{% endblock %}

templates/agence/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Agences{% endblock %}

{% block main %}
    <h1>Agences</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Tel agence</th>
                <th>Adresse</th>
                <th>Ville</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for agence in agences %}
            <tr>
                <td>{{ agence.id }}</td>
                <td>{{ agence.nom }}</td>
                <td>{{ agence.telAgence }}</td>
                <td>{{ agence.adresse }}</td>
                <td>{{ agence.ville }}</td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-sm btn-outline-secondary" href="{{ path('agence_show', {'id': agence.id}) }}">afficher</a>
                        <a class="btn btn-sm btn-outline-secondary" href="{{ path('agence_edit', {'id': agence.id}) }}">modifier</a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">rien à afficher</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('agence_new') }}">Ajouter</a>
{% endblock %}

templates/agence/new.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Agence{% endblock %}

{% block main %}
    <h1>Ajouter Agence</h1>

    {{ include('agence/_form.html.twig') }}

    <a href="{{ path('agence_index') }}">retour vers liste</a>
{% endblock %}

templates/agence/show.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Agence{% endblock %}

{% block main %}
    <h1>Agence</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ agence.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ agence.nom }}</td>
            </tr>
            <tr>
                <th>Tel_agence</th>
                <td>{{ agence.telAgence }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ agence.adresse }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ agence.ville }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('agence_index') }}">retour vers liste</a>

    <a href="{{ path('agence_edit', {'id': agence.id}) }}">modifier</a>

    {{ include('agence/_delete_form.html.twig') }}
{% endblock %}